### ISSUE TITLE
Your website is down

### ISSUE THREAD

**Issue by iam-py-test** [spirillen/ublockorigin-rules#10]
### URL(s) where the issue occurs
`https://www.mypdns.org/T4480`

### Describe the issue
Your website (www.mypdns.org) appears to be down.
As you referenced it in https://github.com/spirillen/ublockorigin-rules/commit/28bb68fa9b3ce22b6ae24bb4dcab09af38f2ce08 I assume that you have not taken it down or changed domain names.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/84232764/120379552-eb8f3200-c2ed-11eb-9cac-8be63764eaa7.png)

[Screenshot(s) for difficult to describe visual issues are **mandatory**.]

### Versions

- Browser/version: Firefox 88.0.1 
- uBlock Origin version: N/A

### Settings

N/A
### Notes
I can confirm with online tools like https://sitecheck.sucuri.net/results/www.mypdns.org and https://www.urlvoid.com/ping-host-ip-online/, so this is not a problem with my device.

**Comment by spirillen** [comment]
Yeps, I know :smile: 

It because my ISP is **bleep** up everything about delivering my new fiber (1000/500mb), So I have been taking the site home a bit to early. (The fiber is still floating around in my front yard :unamused: :angry: )

Don't worry, it should hopefully be back up around the 10th this month, and it is running smoothly on my intranet :smile: 

![image](https://user-images.githubusercontent.com/44526987/120387946-c836a800-c32a-11eb-9f56-aa3d28e5543f.png)

**Comment by iam-py-test** [comment]
> Yeps, I know 😄
> 
> It because my ISP is **bleep** up everything about delivering my new fiber (1000/500mb), So I have been taking the site home a bit to early. (The fiber is still floating around in my front yard 😒 😠 )
> 
> Don't worry, it should hopefully be back up around the 10th this month, and it is running smoothly on my intranet 😄
> 
> ![image](https://user-images.githubusercontent.com/44526987/120387946-c836a800-c32a-11eb-9f56-aa3d28e5543f.png)

OK! I just wanted to make sure you were aware.

**Comment by iam-py-test** [comment]
Should I close this issue?

**Comment by spirillen** [comment]
Yep, no reason for leaving it open.

Another thing I came to think off, you remember we talked about the dig/drill?? you should use them much more along site with curl in your console as they will provide you the real responses without any tracking/spyware sites as you are connecting straight between yourself and the source

```bash
drill -T mypdns.org
.       518400  IN      NS      a.root-servers.net.
...
org.    172800  IN      NS      a0.org.afilias-nst.info.
....
mypdns.org.     86400   IN      NS      ns1.mypdns.org.
mypdns.org.     86400   IN      NS      ns2.mypdns.org.
```

```bash
drill mypdns.org @ns1.mypdns.org
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 13210
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; mypdns.org.  IN      A
```

As you should notice, there are no response from the primary DNS server, there are no connection :+1: 

```bash
curl -I 'https://www.mypdns.org/'
```

You should get something like no route to host

Now you know that there are no resource to be found to get any connection to the domain you are looking for.

Or use https://github.com/funilrys/PyFunceble as it is combining then all together :smiling_imp: 

You can install it with: (Assuming you have python v 3.9.x installed)

```bash
python3.9 -m pip install -U --pre pyfunceble-dev
```

Documentation: https://pyfunceble.readthedocs.io/en/dev/installation/index.html#id1

```bash
pyfunceble -a -u https://www.mypdns.org/
```

![image](https://user-images.githubusercontent.com/44526987/120389782-2a90a800-c32d-11eb-9681-a11d18b4f9aa.png)

```bash
pyfunceble -a -d mypdns.org
```

![image](https://user-images.githubusercontent.com/44526987/120389836-3da37800-c32d-11eb-8674-922c3a1ce593.png)
PS: The output it different from what you'll see as it is active on my intranet.

**Comment by iam-py-test** [comment]
@spirillen Thank you!
Is there anything I can do to contribute to your projects?

**Comment by spirillen** [comment]
Sure, always :smiley:

It depends on what are your interest, what can and will you like to do as there are plenty of small as well as big things that always can need a hand a comment or some enhancements. 

Since everything is opensource we are also open minded :exploding_head: 

You can get a better picture of where you feel like to contribute with when @mypdns is back alive for the public.

Let me no your prefs :open_hands:
