### ISSUE TITLE
Trubled rules

### ISSUE THREAD

**Issue by spirillen** [spirillen/ublockorigin-rules#8]
Hey @Yuki2718 & @THEtomaso Is it possible one of you would help me to understand what's wrong with the following two rules?

https://github.com/spirillen/ublockorigin-rules/blob/282dd5574c5fd32f09714e13a910b0b28b64ab0d/rules/Adult_Annoyance.txt#L537-L538

https://github.com/spirillen/ublockorigin-rules/blob/282dd5574c5fd32f09714e13a910b0b28b64ab0d/rules/anti_whitelist.txt#L41-L43

**Comment by THEtomaso** [comment]
For that first one, you're using a comma, instead of a vertical bar, to seperate the domains.
It should be like this:
`/out.php$document,domain=animeporn.xyz|hot-animal-porn.biz,important`

I don't see anything wrong with the other two.

**Comment by spirillen** [comment]
So to I'll use comma to seperate domains, if they are in front of the Rule and the and/or `|` when it's after the rule?

Is that somewhat right?

**Comment by Yuki2718** [comment]
Vertical line is for `$domain` option. Comma is for cosmetic filters: `example.com,example1.com##.selector`

**Comment by spirillen** [comment]
Thanks

Appreciating your help :smile:
