### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by iam-py-test** [spirillen/ublockorigin-rules#9]
### URL(s) where the issue occurs

`https://spirillen.github.io/ublockorigin-rules/blockrules.txt`

### Describe the issue
There is a typo in the list.
`https://github.com/easylist/easylist/pull/6748`
`/udf-event-track`
should be 
`!https://github.com/easylist/easylist/pull/6748`
`/udf-event-track`

### Screenshot(s)

Strangely GitHub gives me an error when uploading images but a screenshot should not will be needed

### Versions

- Browser/version: N/A
- uBlock Origin version: N/A

### Settings
N/A

**Comment by spirillen** [comment]
Nice spotted, thanks @iam-py-test
